CSSD/Models/ReportViewModel.cs
using CSSD.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CSSD.Models
{
    public class ReportViewModel
    {
        public string Name { get; set; }
        public string Category { get; set; }
        public List<HReportModel> Reports { get; set; }
    }
}

CSSD/Controllers/ReportController.cs
using CSSD.Helper;
using CSSD.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

namespace CSSD.Controllers
{
    public class ReportController : Controller
    {
        private string serverpath = "~/Reports/";

        public ActionResult Index(string name, string category)
        {
            var hreport = new HReport(Server, serverpath);
            var r = new ReportViewModel();
            r.Name = name;
            r.Category = category;
            r.Reports = hreport.List(r.Category);
            return View(r);
        }

        public ActionResult ExportPDF(string category, string filename, string param)
        {
            try
            {
                var server = WebConfigurationManager.AppSettings["reportserver"];
                var database = WebConfigurationManager.AppSettings["reportdatabase"];
                var user = WebConfigurationManager.AppSettings["reportuser"];
                var pass = WebConfigurationManager.AppSettings["reportpass"];

                var hreport = new HReport(Server, serverpath);
                var parameters = JsonConvert.DeserializeObject<List<HReportParameter>>(param);
                var stream = hreport.ExportPDF(server, database, user, pass, category, filename, parameters);

                Response.Buffer = false;
                Response.ClearContent();
                Response.ClearHeaders();
                return File(stream, "application/pdf");
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
    }
}

CSSD/Controllers/Select2Controller.cs
using CSSD.Entities.SIM;
using CSSD.Helper;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CSSD.Controllers
{
    public class Select2Controller : Controller
    {
        #region ===== Transaksi

        [HttpPost]
        public string Other_Linen_Dari(int pagesize, int pageindex, string filter)
        {
            try
            {
                using (var s = new SIMEntities())
                {
                    var proses = s.CSSD_GetLinenDariLinenKotorInternal.AsQueryable();
                    if (!string.IsNullOrEmpty(filter))
                    {
                        proses = proses.Where(x =>
                            x.Kode_Lokasi.Contains(filter) ||
                            x.Nama_Lokasi.Contains(filter)
                        );
                    }
                    var totalcount = proses.Count();
                    var models = proses.OrderBy(x => x.Kode_Lokasi).Skip(pageindex * pagesize).Take(pagesize).ToList();
                    var r = models.ConvertAll(m => new
                    {
                        Id = m.Lokasi_ID,
                        Kode = m.Kode_Lokasi,
                        Nama = m.Nama_Lokasi
                    });
                    return JsonConvert.SerializeObject(new
                    {
                        IsSuccess = true,
                        Data = r,
                        TotalCount = totalcount,
                        PageIndex = pageindex,
                    });
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }

        }
        //#region ===== J A S A

        //[HttpPost]
        //public string Jasa_Jasa_GroupJasa(int pagesize, int pageindex, string filter)
        //{
        //    try
        //    {
        //        using (var s = new SIMEntities())
        //        {
        //            var proses = s.ADM_ListGroupJasa.AsQueryable();
        //            if (!string.IsNullOrEmpty(filter))
        //            {
        //                proses = proses.Where(x =>
        //                    x.GroupJasaName.Contains(filter) ||
        //                    x.KelompokPerawatan.Contains(filter)
        //                );
        //            }
        //            var totalcount = proses.Count();
        //            var models = proses.OrderBy(x => x.GroupJasaName).Skip(pageindex * pagesize).Take(pagesize).ToList();
        //            var r = models.ConvertAll(m => new
        //            {
        //                Id = m.GroupJasaID,
        //                Nama = m.GroupJasaName
        //            });
        //            return JsonConvert.SerializeObject(new
        //            {
        //                IsSuccess = true,
        //                Data = r,
        //                TotalCount = totalcount,
        //                PageIndex = pageindex,
        //            });
        //        }
        //    }
        //    catch (SqlException ex) { return HConvert.Error(ex); }
        //    catch (Exception ex) { return HConvert.Error(ex); }

        //}

        //[HttpPost]
        //public string Jasa_Jasa_KategoriJasa(int pagesize, int pageindex, string filter, byte? groupjasa)
        //{
        //    try
        //    {
        //        using (var s = new SIMEntities())
        //        {
        //            var proses = s.ADM_GetKategoriJasa.AsQueryable();
        //            if (groupjasa != null) proses = proses.Where(x => x.GroupJasa == groupjasa);
        //            if (!string.IsNullOrEmpty(filter))
        //            {
        //                proses = proses.Where(x =>
        //                    x.KategoriJasaID.Contains(filter) ||
        //                    x.NamaInternational.Contains(filter) ||
        //                    x.KategoriJasaName.Contains(filter)
        //                );
        //            }
        //            var totalcount = proses.Count();
        //            var models = proses.OrderBy(x => x.GroupJasaName).Skip(pageindex * pagesize).Take(pagesize).ToList();
        //            var r = models.ConvertAll(m => new
        //            {
        //                Id = m.KategoriJasaID,
        //                Nama = m.KategoriJasaName
        //            });
        //            return JsonConvert.SerializeObject(new
        //            {
        //                IsSuccess = true,
        //                Data = r,
        //                TotalCount = totalcount,
        //                PageIndex = pageindex,
        //            });
        //        }
        //    }
        //    catch (SqlException ex) { return HConvert.Error(ex); }
        //    catch (Exception ex) { return HConvert.Error(ex); }

        //}

        //[HttpPost]
        //public string Jasa_Jasa_Dokter(int pagesize, int pageindex, string filter)
        //{
        //    try
        //    {
        //        using (var s = new SIMEntities())
        //        {
        //            var proses = s.ADM_ListVendor.AsQueryable();
        //            if (!string.IsNullOrEmpty(filter))
        //            {
        //                proses = proses.Where(x =>
        //                    x.Kode_Supplier.Contains(filter) ||
        //                    x.Nama_Supplier.Contains(filter)
        //                );
        //            }
        //            var totalcount = proses.Count();
        //            var models = proses.OrderBy(x => x.Kode_Supplier).Skip(pageindex * pagesize).Take(pagesize).ToList();
        //            var r = models.ConvertAll(m => new
        //            {
        //                Id = m.Kode_Supplier,
        //                Kode = m.Kode_Supplier,
        //                Nama = m.Nama_Supplier
        //            });
        //            return JsonConvert.SerializeObject(new
        //            {
        //                IsSuccess = true,
        //                Data = r,
        //                TotalCount = totalcount,
        //                PageIndex = pageindex,
        //            });
        //        }
        //    }
        //    catch (SqlException ex) { return HConvert.Error(ex); }
        //    catch (Exception ex) { return HConvert.Error(ex); }
        //}

        //[HttpPost]
        //public string Jasa_Jasa_Akun(int pagesize, int pageindex, string filter)
        //{
        //    try
        //    {
        //        using (var s = new SIMEntities())
        //        {
        //            var proses = s.ADM_GetKomponenAkun.AsQueryable();
        //            if (!string.IsNullOrEmpty(filter))
        //            {
        //                proses = proses.Where(x =>
        //                    x.Akun_No.Contains(filter) ||
        //                    x.Akun_Name.Contains(filter)
        //                );
        //            }
        //            var totalcount = proses.Count();
        //            var models = proses.OrderBy(x => x.Akun_No).Skip(pageindex * pagesize).Take(pagesize).ToList();
        //            var r = models.ConvertAll(m => new
        //            {
        //                Id = m.Akun_No,
        //                Kode = m.Akun_No,
        //                Nama = m.Akun_Name
        //            });
        //            return JsonConvert.SerializeObject(new
        //            {
        //                IsSuccess = true,
        //                Data = r,
        //                TotalCount = totalcount,
        //                PageIndex = pageindex,
        //            });
        //        }
        //    }
        //    catch (SqlException ex) { return HConvert.Error(ex); }
        //    catch (Exception ex) { return HConvert.Error(ex); }
        //}

        //[HttpPost]
        //public string Jasa_Jasa_Section(int pagesize, int pageindex, string filter)
        //{
        //    try
        //    {
        //        using (var s = new SIMEntities())
        //        {
        //            var proses = s.ADM_GetLookUpDetailSection.AsQueryable();
        //            if (!string.IsNullOrEmpty(filter))
        //            {
        //                proses = proses.Where(x =>
        //                    x.SectionName.Contains(filter) ||
        //                    x.ID.Contains(filter)
        //                );
        //            }
        //            var totalcount = proses.Count();
        //            var models = proses.OrderBy(x => x.SectionName).Skip(pageindex * pagesize).Take(pagesize).ToList();
        //            var r = models.ConvertAll(m => new
        //            {
        //                Id = m.ID,
        //                Nama = m.SectionName
        //            });
        //            return JsonConvert.SerializeObject(new
        //            {
        //                IsSuccess = true,
        //                Data = r,
        //                TotalCount = totalcount,
        //                PageIndex = pageindex,
        //            });
        //        }
        //    }
        //    catch (SqlException ex) { return HConvert.Error(ex); }
        //    catch (Exception ex) { return HConvert.Error(ex); }
        //}

        //[HttpPost]
        //public string Jasa_Jasa_DataLAB(int pagesize, int pageindex, string filter)
        //{
        //    try
        //    {
        //        using (var s = new SIMEntities())
        //        {
        //            var proses = s.ADM_GetLookUpDetailDataLAB.AsQueryable();
        //            if (!string.IsNullOrEmpty(filter))
        //            {
        //                proses = proses.Where(x =>
        //                    x.ID.Contains(filter) ||
        //                    x.NamaTest.Contains(filter)

CSSD/Views/Report/Index.cshtml
@using CSSD.Models
@using CSSD.Helper
@using Newtonsoft.Json
@model ReportViewModel
@{
    ViewBag.Title = "Report " + Model.Name;
    ViewBag.breadcrumb = new List<SelectListItem>()
{
        new SelectListItem(){ Text = ViewBag.Title, Value = "active" }
    };
}

<table class="table table-bordered table-xxs table-striped">
    <tbody>
        @foreach (var x in Model.Reports)
        {
            if (x.FileName != "sReport.rpt")
            {
                <tr>
                    <td>@x.Title</td>
                    <td style="width:80px;"><button onclick='openmodalreport("@x.FileName")' type="button" class="btn btn-success btn-block btn-xs"><i class="glyphicon glyphicon-print"></i></button></td>
                </tr>
            }
        }
    </tbody>
</table>

<div id="modalreport" class="modal fade" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Report</h4>
            </div>
            <form id="formprint" onsubmit="modalprintonsubmit(this,event)">
                <div class="modal-body">
                    <div class="form-horizontal"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-print"></i> Print</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    let category = '@Model.Category';
    const reportlist = @Html.Raw(JsonConvert.SerializeObject(Model.Reports));

    document.getElementById("formprint").addEventListener('submit', function () {
        this.submit.disabled = true;
    });

    document.addEventListener("DOMContentLoaded", function (event) {
        $('#modaldeletereport').on('shown.bs.modal', function (e) {
            $('#modaldeletereport [type="submit"]').focus();
        });
    });

    const openmodalreport = (filename) => {
        let m = reportlist.find(x => x.FileName === filename);
        let param = '<input type="hidden" name="filename" value="' + filename + '"/>';
        $.each(m.Parameters, function (index, value) {
            let _hide = value.Name.indexOf("@@Copy") === 0 ? 'hide' : '';
            let defvalue = '';

            if (value.Name === '@@Lokasi_ID') _hide = 'hide';
            else if (value.Name === '@@SectionID') _hide = 'hide';
            else if (value.Name === '@@JenisBarangID') _hide = 'hide';

            if (value.Name === '@@SectionID') {
                defvalue = '@Request.Cookies["Inventory_Section_Id"].Value';
            } else if (value.Name === '@@Lokasi_ID') {
                defvalue = '@Request.Cookies["Inventory_Section_LokasiId"].Value';
            } else if (value.Name === '@@JenisBarangID') {
                defvalue = '1';
            } else if (value.Name === '@@SectionName') {
                defvalue = '@Request.Cookies["Inventory_Section_Name"].Value';
            }

            param += '<div class="form-group ' + _hide + '">';
            param += '<label class="control-label col-md-3">';
            param += value.Name.replace('@@', '').split('_').join(' ');
            param += '</label>';
            param += '<div class="col-md-9">';
            if (value.Name === '@@Supplier_ID') {
                param += '<select class="form-control param select-2-supplier" name="' + value.Name + '"></select>';
            }
            @*else if (value.Name === '@@Kelompok') {
                param += '<select class="form-control param select-2" name="' + value.Name + '">';
                param += '@Html.Raw(HList.ReportKelompok)';
                param += '</select>';
            }*@
            else if (value.Name === '@@Kategori') {
                param += '<select class="form-control param select-2-kategori" name="' + value.Name + '"></select>';
            }
            else if (value.ParameterType === 2) {
                param += '<select class="form-control param select-2" name="' + value.Name + '">';
                param += '<option value="">..</option>';
                param += '<option value="TRUE">TRUE</option>';
                param += '<option value="FALSE">FALSE</option>';
                param += '</select>';
            }
            else if (value.Name === '@@Barang_ID') {
                param += '<select class="form-control param select-2-barang" name="' + value.Name + '"></select>';
            }
            else {
                _type =
                    value.ParameterType === 1 ? "number" :
                    value.ParameterType === 3 ? "date" :
                    value.ParameterType === 5 ? "datetime" :
                    value.ParameterType === 6 ? "time" : "text";
                param += '<input class="form-control param" type="' + _type + '" name="' + value.Name + '" value="' + defvalue + '"/>';
            }
            param += '</div>';
            param += '</div>';
        });
        $('#modalreport form .modal-body .form-horizontal').html(param);
        $('#modalreport .select-2').select2();
        initselect2();
        $('#modalreport').modal();
    }

    const initselect2 = () => {

        $('#modalreport .select-2-barang').select2({
            ajax: {
                url: "@Url.Action("Barang", "Select2")",
                dataType: 'json',type: "POST",delay: 250,
                data: function (params) {return {pagesize: 30,pageindex: params.page || 0,filter: params.term};},
                processResults: function (data, params) {
                    if (!data.IsSuccess) alertpopup(data.Message, 'danger');
                    else {
                        params.page = data.PageIndex + 1;
                        return { results: $.map(data.Data, function (value, indel) { return { id: value.Id, text:  value.Kode + ' - ' + value.Nama } }), pagination: { more: (params.page * 30) < data.TotalCount } };
                    }
                }, cache: true
            }
        });

        $('#modalreport .select-2-supplier').select2({
            ajax: {
                url: "@Url.Action("Supplier", "Select2")",
                dataType: 'json',type: "POST",delay: 250,
                data: function (params) {return {pagesize: 30,pageindex: params.page || 0,filter: params.term};},
                processResults: function (data, params) {
                    if (!data.IsSuccess) alertpopup(data.Message, 'danger');
                    else {
                        params.page = data.PageIndex + 1;
                        return { results: $.map(data.Data, function (value, indel) { return { id: value.Kode, text:  value.Kode + ' - ' + value.Nama } }), pagination: { more: (params.page * 30) < data.TotalCount } };
                    }
                }, cache: true
            }
        });

        $('#modalreport .select-2-kategori').select2({
            ajax: {
                url: "@Url.Action("Kategori", "Select2")",
                dataType: 'json',type: "POST",delay: 250,
                data: function (params) {return {pagesize: 30,pageindex: params.page || 0,filter: params.term};},
                processResults: function (data, params) {
                    if (!data.IsSuccess) alertpopup(data.Message, 'danger');
                    else {
                        params.page = data.PageIndex + 1;
                        return { results: $.map(data.Data, function (value, indel) { return { id: value.Id, text:  value.Kode + ' - ' + value.Nama } }), pagination: { more: (params.page * 30) < data.TotalCount } };
                    }
                }, cache: true
            }
        });
    };

    const modalprintonsubmit = (t, e) => {
        e.preventDefault();
        let filename = $('#modalreport form')[0]['filename'].value;
        let param = [];
        let m = reportlist.find(x => x.FileName === filename);
        $.each($('#modalreport form .param'), function (index, value) {
            let _param = m.Parameters.find(y => y.Name === value.name);
            param.push({
                Name: _param.Name,
                ParameterType: _param.ParameterType,
                Value: value.value
            });
        });
        window.open('@Url.Action("ExportPDF")?category=@(Model.Category)&filename=' + filename + '&param=' + encodeURIComponent(JSON.stringify(param)), '_blank');
        $('#modalreport').modal('hide');
    }
</script>