CSSD/Models/Setup/KontrakVendorModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CSSD.Models.Setup
{
    public class KontrakVendorModel
    {
        public string Kode_Barang { get; set; }
        public string Nama_Barang { get; set; }
        public string Nama_Supplier { get; set; }
        public string Kode_Item { get; set; }
        public string Nama_Item { get; set; }
        public int? Barang_ID { get; set; }
        public short? SupplierID { get; set; }
        public short? Supplier_ID { get; set; }
        public string Kode_Supplier { get; set; }
        public string Supplier_Nama_Supplier { get; set; }
        public decimal? Harga { get; set; }

    }
}

CSSD/Controllers/ReportController.cs
using CSSD.Helper;
using CSSD.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

namespace CSSD.Controllers
{
    public class ReportController : Controller
    {
        private string serverpath = "~/Reports/";

        public ActionResult Index(string name, string category)
        {
            var hreport = new HReport(Server, serverpath);
            var r = new ReportViewModel();
            r.Name = name;
            r.Category = category;
            r.Reports = hreport.List(r.Category);
            return View(r);
        }

        public ActionResult ExportPDF(string category, string filename, string param)
        {
            try
            {
                var server = WebConfigurationManager.AppSettings["reportserver"];
                var database = WebConfigurationManager.AppSettings["reportdatabase"];
                var user = WebConfigurationManager.AppSettings["reportuser"];
                var pass = WebConfigurationManager.AppSettings["reportpass"];

                var hreport = new HReport(Server, serverpath);
                var parameters = JsonConvert.DeserializeObject<List<HReportParameter>>(param);
                var stream = hreport.ExportPDF(server, database, user, pass, category, filename, parameters);

                Response.Buffer = false;
                Response.ClearContent();
                Response.ClearHeaders();
                return File(stream, "application/pdf");
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
    }
}

CSSD/Controllers/Setup/KontrakVendorController.cs
using CSSD.Entities.SIM;
using CSSD.Helper;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;
using System.Linq.Dynamic;
using CSSD.Models.Setup;

namespace CSSD.Controllers.Setup
{
    public class KontrakVendorController : Controller
    {
        // GET: KontrakVendor
        #region ===== L I S T

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public string List(string orderby, bool orderbytype, int pagesize, int pageindex, List<FilterModel> filter)
        {
            try
            {
                int totalcount;
                using (var s = new SIMEntities())
                {
                    var proses = s.CSSD_ListSetupKontrak.AsQueryable();
                    foreach (var x in filter)
                    {
                        if (x.Key == "All" && !string.IsNullOrEmpty(x.Value))
                            proses = proses.Where(y => y.Kode_Item.Contains(x.Value) || 
                                                       y.Nama_Item.Contains(x.Value) ||
                                                       y.Kode_Supplier.Contains(x.Value) ||
                                                       y.Supplier_Nama_Supplier.Contains(x.Value) 
                                                       );

                    }
                    totalcount = proses.Count();
                    var models = proses.OrderBy($"{orderby} {(orderbytype ? "ASC" : "DESC")}").Skip((pageindex) * pagesize).Take(pagesize).ToList();
                    var r = models.ConvertAll(x => new
                    {
                        Kode_Item = x.Kode_Item,
                        Nama_Item = x.Nama_Item,
                        Kode_Supplier = x.Kode_Supplier,
                        Supplier_Nama_Supplier = x.Supplier_Nama_Supplier,
                        Harga = x.Harga,

                    }); ;
                    return JsonConvert.SerializeObject(new { IsSuccess = true, Data = r, TotalCount = totalcount });
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }
        }

        #endregion

        #region ===== S E T U P

        [HttpPost]
        public string Save(string _process, KontrakVendorModel model)
        {
            using (var s = new SIMEntities())
            {
                using (var dbContextTransaction = s.Database.BeginTransaction())
                {
                    try
                    {
                        var userid = User.Identity.GetUserId();
                        var id = 0;
                        if (_process == "CREATE")
                        {
                            id = s.CSSD_InsertSetupKontrak(model.SupplierID, model.Barang_ID, model.Harga);
                            s.SaveChanges();
                        }
                        else if (_process == "EDIT")
                        {
                            s.CSSD_UpdateSetupKontrak(model.SupplierID, model.Barang_ID, model.Harga);
                            s.SaveChanges();
                        }
                        else if (_process == "DELETE")
                        {
                            s.CSSD_DeleteSetupKontrak(model.SupplierID, model.Barang_ID, model.Harga);
                            s.SaveChanges();
                        }

                        var userActivity = new UserActivityModel(Request, User.Identity.GetUserId())
                        {
                            Activity = $"SetupKontrakVendor-{_process}; id:{id};".ToLower()
                        };
                        UserActivity.InsertUserActivity(userActivity);
                        dbContextTransaction.Commit();
                    }
                    catch (SqlException ex) { dbContextTransaction.Rollback(); return HConvert.Error(ex); }
                    catch (Exception ex) { dbContextTransaction.Rollback(); return HConvert.Error(ex); }
                }
            }
            return HConvert.Success();
        }

        [HttpPost]
        public string Detail(string id)
        {
            try
            {
                using (var s = new SIMEntities())
                {
                    var m = s.CSSD_ListSetupKontrak.FirstOrDefault(x => x.Kode_Item == id);
                    if (m == null) throw new Exception("Data tidak ditemukan");
                    return JsonConvert.SerializeObject(new
                    {
                        IsSuccess = true,
                        Data = new
                        {
                            SupplierID = m.SupplierID,
                            Barang_ID = m.Barang_ID,
                            Kode_Barang = m.Kode_Item,
                            Nama_Barang = m.Nama_Item,
                            Kode_Supplier = m.Kode_Supplier,
                            Nama_Supplier = m.Supplier_Nama_Supplier,
                            Harga = m.Harga,
                        }
                    });
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }
        }

        #endregion

        #region ===== L O O K U P 

        [HttpPost]
        public string ListLookupBarang(string orderby, bool orderbytype, int pagesize, int pageindex, List<FilterModel> filter)
        {
            try
            {
                int totalcount;
                using (var s = new SIMEntities())
                {
                    var proses = s.CSSD_GetBarangSetupKontrak.AsQueryable();
                    foreach (var x in filter)
                    {
                        if (x.Key == "All" && !string.IsNullOrEmpty(x.Value))
                            proses = proses.Where(y =>
                                y.Kode_Barang.Contains(x.Value) ||
                                y.Nama_Barang.Contains(x.Value));
                    }
                    totalcount = proses.Count();
                    var models = proses.OrderBy($"{orderby} {(orderbytype ? "ASC" : "DESC")}").Skip((pageindex) * pagesize).Take(pagesize).ToList();
                    var r = models.ConvertAll(x => new
                    {
                        Barang_ID = x.Barang_ID,
                        Kode_Barang = x.Kode_Barang,
                        Nama_Barang = x.Nama_Barang,
                    });
                    return JsonConvert.SerializeObject(new { IsSuccess = true, Data = r, TotalCount = totalcount });
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }
        }
        public string ListLookupSupplier(string orderby, bool orderbytype, int pagesize, int pageindex, List<FilterModel> filter)
        {
            try
            {
                int totalcount;
                using (var s = new SIMEntities())
                {
                    var proses = s.CSSD_GetSupplierSetupKontrak.AsQueryable();
                    foreach (var x in filter)
                    {
                        if (x.Key == "All" && !string.IsNullOrEmpty(x.Value))
                            proses = proses.Where(y =>
                                y.Kode_Supplier.Contains(x.Value) ||
                                y.Nama_Supplier.Contains(x.Value));
                    }
                    totalcount = proses.Count();
                    var models = proses.OrderBy($"{orderby} {(orderbytype ? "ASC" : "DESC")}").Skip((pageindex) * pagesize).Take(pagesize).ToList();
                    var r = models.ConvertAll(x => new
                    {
                        SupplierID = x.Supplier_ID,
                        Kode_Supplier = x.Kode_Supplier,
                        Nama_Supplier = x.Nama_Supplier,
                    });
                    return JsonConvert.SerializeObject(new { IsSuccess = true, Data = r, TotalCount = totalcount });
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }
        }

        #endregion
    }
}

CSSD/Views/PenerimaanLinenDariVerndor/Index.cshtml
@{
    ViewBag.Title = "Penerimaan Barang";
    ViewBag.breadcrumb = new List<SelectListItem>()
{
        new SelectListItem(){ Text = ViewBag.Title, Value = "active" }
    };
}
@using CSSD.Helper
@using Microsoft.AspNet.Identity

<style>
    .itable-status.bg-grey-300 a:hover {
        background-color: #999;
    }

    .itable-status.bg-primary-300 a:hover {
        background-color: #64b5f6;
    }

    .itable-hide-po thead th:nth-child(3),
    .itable-hide-po tbody td:nth-child(3) {
        display: none;
    }
</style>

<form id="formtable">
    <div class="panel panel-flat">
        <div class="panel-heading">
            <div class="panel-title"></div>
            <div class="heading-elements">
                <ul class="icons-list">
                    <li><a class="panel-action action-filter" href="javascript:itable.openfilter()"></a></li>
                </ul>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-2">
                <label>Filter</label>
                <input type="text" data-itable-filter="All" name="all" value="" class="form-control" />
            </div>
            <div class="col-md-2">
                <label>Dari Tanggal</label>
                <input type="date" name="periode" data-itable-filter="PeriodeStart" class="form-control" value="@(DateTime.Today.ToString("yyyy-MM-dd"))" />
            </div>
            <div class="col-md-2">
                <label>Sampai Tanggal</label>
                <input type="date" name="sampai" data-itable-filter="PeriodeEnd" class="form-control" value="@(DateTime.Today.ToString("yyyy-MM-dd"))" />
            </div>
            @*<label class="control-label col-md-2">Show</label>*@
            <div class="col-md-1">
                <label>Page</label>
                <select class="form-control itable-pagesize" style="width: auto;" name="show">
                    <option selected>10</option>
                    <option>25</option>
                    <option>50</option>
                    <option>100</option>
                </select>
            </div>
            <div class="col-md-2">
                <button type="submit" style="margin-top : 27px" class="btn-save btn btn-primary"><i class="icon icon-search4"></i>Cari</button>
            </div>
        </div>
        <div class="dataTables_wrapper no-footer" style="display: block;">
            <div class="datatable-header">
                <input type="hidden" data-itable-filter="Realisasi" value="Realisasi" />
            </div>
            <ul class="nav nav-pills nav-pills-toolbar nav-justified" style="margin-bottom:0;">
                <li class="itable-status bg-primary-300"><a onclick="itable.changestatus('Realisasi', this)">Realisasi</a></li>
                <li class="itable-status"><a onclick="itable.changestatus('Open', this)">Open</a></li>
            </ul>
            <div class="datatable-scroll">
                <table class="table datatable-basic dataTable no-footer table-xxs table-striped">
                    <thead>
                        <tr>
                            <th class="sorting" data-itable-sorting="Tgl_Penerimaan" style="width: 100px;">Tanggal<i></i></th>
                            <th class="sorting" data-itable-sorting="No" style="width: 180px;">No <i></i></th>
                            <th class="sorting" data-itable-sorting="No_DO">No DO<i></i></th>
                            <th class="sorting" data-itable-sorting="Supplier">Supplier<i></i></th>
                            <th class="text-center sorting_disabled" style="width: 100px;">Actions</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
            <div class="datatable-footer">
                <div class="dataTables_info itable-info"></div>
                <div class="dataTables_paginate paging_simple_numbers itable-pagination"></div>
            </div>
        </div>
    </div>
</form>

<div id="modalfilter" class="modal fade" role="dialog">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <form autocomplete="off" onsubmit="itable.filtersubmit(this,event)">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Filter</h4>
                </div>
                <div class="modal-body">
                    <div class="form-horizontal">
                        <div class="form-group">
                            <label class="control-label col-md-4">Filter</label>
                            <div class="col-md-8">
                                <input type="text" name="all" class="form-control" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4">Periode</label>
                            <div class="col-md-8">
                                <input type="date" name="periode" class="form-control" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4">Sampai</label>
                            <div class="col-md-8">
                                <input type="date" name="sampai" class="form-control" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4">Show</label>
                            <div class="col-md-8">
                                <select class="form-control" style="width: auto;" name="show">
                                    <option selected>10</option>
                                    <option>25</option>
                                    <option>50</option>
                                    <option>100</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn-save btn btn-primary"><i class="icon icon-check"></i> OK</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    var itable;
    document.addEventListener("DOMContentLoaded", function (event) {
        itable = new iTable({
            url: '@Url.Action("List")',
            table: document.getElementById('formtable'),
            orderby: 'No_Penerimaan',
            orderbytype: false,
            tablesuccess: function (r, t) {
                if (r.IsSuccess) {
                    var tbody = '';
                    if (r.Data.length === 0)
                        tbody += '<tr><td colspan="5" class="text-center">----- <b>Tidak ada data</b> -----</td></tr>';
                    $.each(r.Data, function (index, value) {
                        tbody += '<tr class="alpha-' + status + '">';

                        // column
                        tbody += '<td class="text-center">' + value.Tanggal + '</td>';
                        tbody += '<td>' + value.No + '</td>';
                        tbody += '<td>' + (value.NoDO || '-') + '</td>';
                        tbody += '<td>' + value.Supplier + '</td>';

                        tbody += '<td class="text-center">';
                        tbody += '<ul class="icons-list">';
                        tbody += '<li class="dropdown">';
                        tbody += '<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-menu9"></i></a>';
                        tbody += '<ul class="dropdown-menu dropdown-menu-right">';

                        // action
                        if (value.Realisasi) {
                            tbody += '<li><a href="javascript:isetup.opensetup(\'VIEW\', { id : \'' + value.No + '\'})"><i class="icon-eye"></i> View</a></li>';
                            tbody += '<li><a href="javascript:isetup.opensetup(\'DELETE\', { id : \'' + value.No + '\'})"><i class="icon-trash"></i> Delete</a></li>';
                        } else {
                            tbody += '<li><a href="javascript:isetup.opensetup(\'CREATE\',{ id : \'' + value.No + '\'})"><i class="icon-download"></i> Terima</a></li>';
                        }

                        tbody += '</ul>';
                        tbody += '</li>';
                        tbody += '</ul>';
                        tbody += '</td>';
                        tbody += '</tr>';
                    });
                    $(t.table).find('tbody').html(tbody);
                    var footer = generatefootertable(r.TotalCount, t.pagesize, t.pageindex, 'tableordergetdatas');
                    $(t.table).find('.itable-info').html(footer.datainfo);
                    $(t.table).find('.itable-pagination').html(footer.pagination);
                } else {
                    alert(r.Message);
                }
            }
        });

        itable.refresh();

        itable.openfilter = function () {
            var f = $('#modalfilter form')[0];
            f['periode'].value = $('#formtable [data-itable-filter="PeriodeStart"]')[0].value;
            f['sampai'].value = $('#formtable [data-itable-filter="PeriodeEnd"]')[0].value;
            f['all'].value = $('#formtable [data-itable-filter="All"]')[0].value;
            f['show'].value = $('#formtable .itable-pagesize')[0].value;
            $('#modalfilter').modal();
        }

        itable.filtersubmit = function (t, e) {
            e.preventDefault();
            var f = $('#modalfilter form')[0];
            $('#formtable [data-itable-filter="PeriodeStart"]')[0].value = f['periode'].value;
            $('#formtable [data-itable-filter="PeriodeEnd"]')[0].value = f['sampai'].value;
            $('#formtable [data-itable-filter="All"]')[0].value = f['all'].value;
            $('#formtable .itable-pagesize')[0].value = f['show'].value;
            itable.pageindex = 0;
            itable.refresh();
            $('#modalfilter').modal('hide');
        }

        itable.changestatus = (status, t) => {
            $('#formtable .itable-status').removeClass('bg-grey-300');
            $('#formtable .itable-status').removeClass('bg-primary-300');
            if (status === 'Realisasi') {
                $(t).closest('li').addClass('bg-primary-300');
                $(itable.table).removeClass('itable-hide-po');
                $(itable.table).find('[data-itable-sorting="No_Penerimaan"]').html("No Penerimaan");
            } else {
                $(t).closest('li').addClass('bg-grey-300');
                $(itable.table).addClass('itable-hide-po');
                $(itable.table).find('[data-itable-sorting="No_Penerimaan"]').html("No Order");
            }
            $('#formtable [data-itable-filter="Realisasi"]').val(status);
            itable.pageindex = 0;
            itable.refresh();
        };
    });
</script>
@Html.Partial("Setup")
@Html.Partial("_LookUpSupplier")


@*tbody += '<li><a target="_blank" href="@Url.Action("ExportPDF", "Report", new { category = "Transaksi", filename= "SIM_Rpt_FOrm_Penerimaan.rpt" })&param=[{\'Name\':\'@@NoPenerimaan\',\'ParameterType\':4,\'Value\':\'' + value.No + '\'}]"><i class="icon-printer"></i> Report</a></li>';*@

CSSD/Views/PenerimaanLinenDariVerndor/_LookUpSupplier.cshtml
<style>
    #modallookupsupplier table td,
    #modallookupsupplier table th {
        white-space: nowrap;
    }
</style>
<div id="modallookupsupplier" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Supplier</h4>
            </div>
            <form id="lookupsupplier">
                <div class="dataTables_wrapper no-footer" style="display: block;">
                    <div class="datatable-header" style="padding-bottom:15px;">
                        <div class="form-inline">
                            <div class="form-group">
                                <label>Filter</label>
                                <input type="search" class="form-control" data-itable-filter="All" data-itable-filter-type="contains" placeholder="Type to filter...">
                            </div>
                            <div class="form-group hide">
                                <label>Show</label>
                                <select class="form-control itable-pagesize" style="width: auto;" onchange="modallookupsupplier.refresh()">
                                    <option selected>10</option>
                                    <option>25</option>
                                    <option>50</option>
                                    <option>100</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="datatable-scroll table-responsive">
                        <table class="table datatable-basic dataTable no-footer table-xxs table-striped table-lookup" role="grid" aria-describedby="DataTables_Table_0_info">
                            <thead>
                                <tr>
                                    <th class="sorting" data-itable-sorting="SupplierID">Supplier ID<i></i></th>
                                    <th class="sorting" data-itable-sorting="Kode_Supplier">Kode Supplier<i></i></th>
                                    <th class="sorting" data-itable-sorting="Nama_Supplier">Nama Supplier<i></i></th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                    <div class="datatable-footer">
                        <div class="dataTables_info itable-info"></div>
                        <div class="dataTables_paginate paging_simple_numbers itable-pagination"></div>
                    </div>
                </div>
            </form>
            <div class="modal-footer">
                <button type="button" class="btn-save btn btn-primary" onclick="modallookupsupplier.selected(this)"><i class="glyphicon icon-check"></i> SELECT</button>
            </div>
        </div>
    </div>
</div>

<script>
    var modallookupsupplier;
    document.addEventListener("DOMContentLoaded", function (event) {
        modallookupsupplier = new iTable({
            url: '@Url.Action("ListLookupSupplier")',
            table: document.getElementById('lookupsupplier'),
            orderby: 'Supplier_ID',
            orderbytype: true,
            tablesuccess: function (r, t) {
                if (r.IsSuccess) {
                    $(t.table).find('tbody').html('');
                    if (r.Data.length === 0)
                        $(t.table).find('tbody').append('<tr><td colspan="9" class="text-center">----- <b>Tidak ada data</b> -----</td></tr>');
                    $.each(r.Data, function (index, value) {
                        var tbody = '<tr class="odd" onclick="modallookupsupplier.detailactive(this)">';

                        // column
                        tbody += '<td>' + value.SupplierID + '</td>';
                        tbody += '<td>' + value.Kode_Supplier + '</td>';
                        tbody += '<td>' + value.Nama_Supplier + '</td>';
                        tbody += '</tr>';
                        $(t.table).find('tbody').append(tbody);
                        $(t.table).find('tbody tr').last().data('model', JSON.stringify(value));
                    });
                    var footer = generatefootertable(r.TotalCount, t.pagesize, t.pageindex, 'tableordergetdatas');
                    $(t.table).find('.itable-info').html(footer.datainfo);
                    $(t.table).find('.itable-pagination').html(footer.pagination);
                } else {
                    alert(r.Message);
                }
            }
        });

        modallookupsupplier.openmodal = function(t) {
            modallookupsupplier.refresh();
            $('#modallookupsupplier').modal();
            $('.modal-backdrop:last').css('z-index', $('#modallookupsupplier').css('z-index') - 1);
        }

        modallookupsupplier.clear = () => {
            isetup.form['SupplierID'].value = '';
            isetup.form['Kode_Supplier'].value = '';
            isetup.form['Nama_Supplier'].value = '';
        };

        modallookupsupplier.detailactive = function(t) {
            if ($(t).hasClass('bg-primary')) {
                modallookupsupplier.selected(t);
            } else {
                $(t).closest('tbody').find('.bg-primary').removeClass('bg-primary');
                $(t).addClass('bg-primary');
            }
        }

        modallookupsupplier.selected = function(t) {
            var model = JSON.parse($(t).closest('.modal').find('table tbody tr.bg-primary').data('model'));
            isetup.form['SupplierID'].value = model.SupplierID;
            isetup.form['Kode_Supplier'].value = model.Kode_Supplier;
            isetup.form['Nama_Supplier'].value = model.Nama_Supplier;
            $(t).closest('.modal').modal('hide');
        }

        $('#modallookupsupplier').on('hidden.bs.modal', function () { $('body').addClass('modal-open'); });
    });
</script>